database:
  client: "mysql"
  connection:
    host: "localhost"
    port: 3306
    database: "meme_project_db"
    user: "your_username"
    password: "your_password"
  
server:
  host: "localhost"
  port: 8055

admin:
  email: "admin@example.com"
  password: "admin_password"

cors:
  enabled: true
  origin: "*"

jwt:
  secret: "your_jwt_secret"

uploads:
  maxFileSize: 10485760  # 10 MB
  adapter: "local"
  options:
    folder: "./uploads"